# Generated by Django 3.2.9 on 2021-11-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='isCorrect',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='result_student_answer',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
